---
- name: template setup
  ansible.builtin.setfacts:
    also_for:
      snapshot: "UNRELEASED"
      stable: "perfsonar-{{ release }} perfsonar-release perfsonar-minor-staging"
    distributions_tpl:
      Origin: "perfSONAR"
      Label: "perfsonar.net"
      Codename: "perfsonar-5.0-__mode__"
      Description: "perfSONAR Debian repository for {{ release }} release - __mode__ packages"
      Architectures: "amd64 armel armhf arm64 ppc64el source"
      Components: "main"
      Tracking: "minimal"
      SignWith: "8968F5F6"
