---

- name: Restart rsync
  ansible.builtin.service:
    name: rsync
    state: restarted
  become: true

- name: Restart apache
  ansible.builtin.service:
    name: apache2
    state: restarted
  become: true

- name: Restart sshd
  ansible.builtin.service:
    name: sshd
    state: restarted
  become: true

- name: Systemd daemon-reload
  ansible.builtin.systemd:
    daemon_reload: true
  become: true

- name: Goaccess restart
  ansible.builtin.systemd:
    enabled: true
    name: goaccess
    state: restarted
  become: true
